services:
  linux:
    build:
      context: ./docker/linux
    image: fyne-cross-custom:linux
    x-bake:
      tags:
        - fyne-cross-custom:linux
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm64/v8
      pull: false