services:
  linux:
    build:
      context: ./docker/linux
    image: fyne-cross-custom:amd64
    platform: linux/amd64
    x-bake:
      tags:
        - fyne-cross-custom:amd64
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm64/v8
      pull: false
  linux-arm64:
    build:
      context: ./docker/linux
    image: fyne-cross-custom:arm64
    platform: linux/arm64
    x-bake:
      tags:
        - fyne-cross-custom:arm64
      platforms:
        - linux/arm64
      pull: false